### ISSUE TITLE
To Query geometry function like ST_contains

### ISSUE THREAD

**Issue by sudeepdestiny** [PanierAvide/OSM2Hive#1]
How to query with node,way & relation tables to use geometry function like St_contains?

**Comment by PanierAvide** [comment]
Hello, you can use ESRI open source user-defined functions here :
https://github.com/Esri/spatial-framework-for-hadoop
I'm closing the issue as it is not directly related to this project, but let me know if you have questions.

**Comment by sudeepdestiny** [comment]
Yeah that's true. But how can we understand a polygon or poly line with node , way and relation. For Points like POI, can use node lat long as input.

**Comment by PanierAvide** [comment]
You have to create a first table where you re-construct the lines and polygons according to way/relation tables. Then, you will be able to query them.
